#
# Vivado (TM) v2014.4 (64-bit)
#
# build.tcl: Tcl script for re-creating project 'X-4'
#
# Generated by Vivado on Sat Feb 27 17:32:18 EST 2016
# IP Build 1070531 on Tue Nov 18 01:10:18 MST 2014
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/src/vmm_global_reset.vhd"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/src/vmm_acq_reset.vhd"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/src/scope_select.vhd"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/component.xml"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/ip/fifo_64_32_512/fifo_64_32_512.xci"
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/src/vmm_daq.vhd"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/src/vmm_cfg_sr.vhd"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/src/vmm_pkg.vhd"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/src/vmm_cfg.vhd"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/bd/mbsys/mbsys.bd"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/src/leaky_readout.vhd"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/src/external_trigger.vhd"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/src/toplevel.vhd"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/src/vmm_cfg_rst.vhd"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/ip/ila_1/ila_1.xci"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/ip/clk_wiz_200_to_400/clk_wiz_200_to_400.xci"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/ip/clk_wiz_low_jitter/clk_wiz_low_jitter.xci"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xci"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/ip/ila_leaky/ila_leaky.xci"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/ip/ila_ext_trig/ila_ext_trig.xci"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/ip/fifo_leaky/fifo_leaky.xci"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/ip/fifo_round_robin/fifo_round_robin.xci"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/ip/fifo_daq/fifo_daq.xci"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/sources_1/ip/ila_top/ila_top.xci"
#    "/home/mmfe8/Desktop/versioning/X-4b2h-XADC/X-4.srcs/constrs_1/imports/new/toplevel.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project mmfe8 ./mmfe8

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects mmfe8]
set_property "default_lib" "xil_defaultlib" $obj
set_property "part" "xc7a200tfbg484-2" $obj
set_property "simulator_language" "Mixed" $obj
set_property "target_language" "VHDL" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/srcs/sources_1/src/vmm_global_reset.vhd"]"\
 "[file normalize "$origin_dir/srcs/sources_1/src/vmm_daq.vhd"]"\
 "[file normalize "$origin_dir/srcs/sources_1/src/vmm_cfg_sr.vhd"]"\
 "[file normalize "$origin_dir/srcs/sources_1/src/vmm_acq_reset.vhd"]"\
 "[file normalize "$origin_dir/srcs/sources_1/src/vmm_pkg.vhd"]"\
 "[file normalize "$origin_dir/srcs/sources_1/src/vmm_cfg.vhd"]"\
 "[file normalize "$origin_dir/srcs/sources_1/src/scope_select.vhd"]"\
 "[file normalize "$origin_dir/srcs/sources_1/bd/mbsys/mbsys.bd"]"\
 "[file normalize "$origin_dir/srcs/sources_1/src/leaky_readout.vhd"]"\
 "[file normalize "$origin_dir/srcs/sources_1/src/external_trigger.vhd"]"\
 "[file normalize "$origin_dir/srcs/sources_1/src/toplevel.vhd"]"\
 "[file normalize "$origin_dir/srcs/sources_1/src/vmm_cfg_rst.vhd"]"\
 "[file normalize "$origin_dir/srcs/component.xml"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/srcs/sources_1/src/vmm_daq.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/srcs/sources_1/src/vmm_cfg_sr.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/srcs/sources_1/src/vmm_pkg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/srcs/sources_1/src/vmm_cfg.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/srcs/sources_1/bd/mbsys/mbsys.bd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "0" $file_obj
}

set file "$origin_dir/srcs/sources_1/src/leaky_readout.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/srcs/sources_1/src/external_trigger.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/srcs/sources_1/src/toplevel.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/srcs/sources_1/src/vmm_cfg_rst.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sources_1' fileset file properties for local files
set file "src/vmm_global_reset.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "src/vmm_acq_reset.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "src/scope_select.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "srcs/component.xml"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP-XACT" $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "toplevel" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "synth_checkpoint_mode" "Singular" $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/srcs/sources_1/ip/ila_1/ila_1.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "synth_checkpoint_mode" "Singular" $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/srcs/sources_1/ip/clk_wiz_200_to_400/clk_wiz_200_to_400.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/srcs/sources_1/ip/clk_wiz_200_to_400/clk_wiz_200_to_400.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "synth_checkpoint_mode" "Singular" $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/srcs/sources_1/ip/clk_wiz_low_jitter/clk_wiz_low_jitter.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/srcs/sources_1/ip/clk_wiz_low_jitter/clk_wiz_low_jitter.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "synth_checkpoint_mode" "Singular" $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "synth_checkpoint_mode" "Singular" $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/srcs/sources_1/ip/ila_leaky/ila_leaky.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/srcs/sources_1/ip/ila_ext_trig/ila_ext_trig.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/srcs/sources_1/ip/fifo_leaky/fifo_leaky.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/srcs/sources_1/ip/fifo_leaky/fifo_leaky.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "synth_checkpoint_mode" "Singular" $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/srcs/sources_1/ip/fifo_round_robin/fifo_round_robin.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/srcs/sources_1/ip/fifo_round_robin/fifo_round_robin.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "synth_checkpoint_mode" "Singular" $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/srcs/sources_1/ip/fifo_daq/fifo_daq.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/srcs/sources_1/ip/fifo_daq/fifo_daq.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "synth_checkpoint_mode" "Singular" $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/srcs/sources_1/ip/ila_top/ila_top.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/srcs/sources_1/ip/fifo_64_32_512/fifo_64_32_512.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_64_32_512/fifo_64_32_512.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "synth_checkpoint_mode" "Singular" $file_obj
}


# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/srcs/constrs_1/imports/new/toplevel.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/srcs/constrs_1/imports/new/toplevel.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property "target_constrs_file" "$orig_proj_dir/srcs/constrs_1/imports/new/toplevel.xdc" $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "toplevel" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7a200tfbg484-2 -flow {Vivado Synthesis 2014} -strategy "My test" -constrset constrs_1
} else {
  set_property strategy "My test" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2014" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "needs_refresh" "1" $obj
set_property "part" "xc7a200tfbg484-2" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7a200tfbg484-2 -flow {Vivado Implementation 2014} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2014" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "needs_refresh" "1" $obj
set_property "part" "xc7a200tfbg484-2" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:mmfe8"
